language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:george-edison55/precise-backports
    - sudo apt-get update -qq
    - sudo apt-get install cmake cmake-data -y

before_script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DOCTASPIRE_EASING_COVERAGE:BOOL=ON ..

script:
    - make
    - test/octaspire-easing-test-runner
    - cd test/CMakeFiles/octaspire-easing-test-runner.dir
    - gcov *.gcno

after_success:
      - bash <(curl -s https://codecov.io/bash)

