language: c

compiler:
    - clang
    - gcc

before_script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DOCTASPIRE_EASING_COVERAGE:BOOL=ON ..

script:
    - make
    - test/octaspire-easing-test-runner
    - cd test/CMakeFiles/octaspire-easing-test-runner.dir
    - gcov *.gcno

after_success:
      - bash <(curl -s https://codecov.io/bash)

